/** Mutable simulator state shared across modules. */

export const state = {
  CONFIG: null,
  JOINTS: [],
  joints: {},
  activePose: null,
  UNIT: "mm",
  apiReady: false,

  scene: null,
  camera: null,
  controls: null,
  renderer: null,
  labelRenderer: null,
  grid: null,

  baseGroup: null,
  armRotateGroup: null,
  shoulderGroup: null,
  elbowGroup: null,
  wristGroup: null,
  wristRotGroup: null,
  gripperGroup: null,
  fingerL: null,
  fingerR: null,
  tipMarker: null,
  tipCoordLabel: null,
  dimX: null,
  dimY: null,
  dimZ: null,

  valEls: {},
  homeCam: null,

  angleGroup: null,
  angleLines: null,
  angleLabels: null,
  showAngles: true,
  showLengthLabels: true,
  lengthLabels: [],

  freeSwing: false,
  calLabOpen: false,
  calJoint: "elbow_flex",

  reachCloud: null,
  reachFloor: null,
  reachBounds: null,
  showReach: true,
  reachKinCoords: [],
  reachAllSamples: [],
  reachFilterZ: 0,
  reachZTolerance: 10,
  reachRaycaster: null,
  reachMouse: null,
  reachPointerDown: { x: 0, y: 0 },
  reachHoverPt: null,
  reachCopiedTimer: null,
  reachLastPointer: { x: 0, y: 0 },
  reachAnimFrame: null,

  fingerRestZ: 12,
  tipWorld: null,
  wristWorld: null,

  pitchArrow: null,
  pitchMode: "auto",
};
